# -*- coding: utf-8 -*-
"""Part 3: tickets, notes, time, attachments, analytics, control panel, assistant, ops."""
from qa_plan_part1 import mod

mod("11. Ticket Lifecycle in the Portal",
    "Viewing, creating, assigning and changing tickets, and pushing those changes to the PSA.",
    [
     ("TKT-01", "Ticket list and filters",
      "Open /dashboard/tickets and filter by status, queue, technician and unassigned.",
      "Counts match SQL for the same filter.",
      "Browser + SQL."),
     ("TKT-02", "Ticket detail renders fully",
      "Open a ticket with notes, time entries and attachments.",
      "Properties rail, conversation, time panel and attachments all render, no console errors.",
      "Browser DevTools console."),
     ("TKT-03", "Create a ticket from the portal",
      "/dashboard/tickets/new, fill required fields, submit.",
      "Created in the PSA FIRST, then stored locally with the returned external id.",
      "PSA UI + SQL: \"ExternalTicketId\" is populated, not null."),
     ("TKT-04", "Status change pushes to the PSA",
      "POST /api/tickets/{id}/status or use the UI control.",
      "The PSA reflects the new status; the portal shows the mapped value.",
      "PSA UI. Then let a sync run and confirm it is not re-applied as an inbound change."),
     ("TKT-05", "Rejected status change surfaces the real reason",
      "Attempt a status the PSA will refuse (for example one from another board).",
      "The provider's own message is shown, not 'Still rejected' or a generic error, and the "
      "stored error is from THIS attempt, not the previous one.",
      "Browser. Compare the row's UpdatedAt with the time of your attempt."),
     ("TKT-06", "Assignment",
      "GET /api/tickets/{id}/assignees then PUT /api/tickets/{id}/assignment.",
      "Only technicians who cover that queue are offered; the PSA is updated.",
      "PSA UI."),
     ("TKT-07", "Service instructions surface",
      "Set account-level instructions in the Control Panel, then open a ticket for that account.",
      "The amber instructions panel shows the account override, falling back to the global text.",
      "Browser."),
     ("TKT-08", "Ticket page hides staff tooling from clients",
      "Open the same ticket as a client user.",
      "Time panel, assignment and status controls absent; the time query is not even issued.",
      "Browser network tab."),
     ("TKT-09", "SLA and dates display",
      "Open a ticket with an SLA target.",
      "Raise date, SLA due and closure date display and match the PSA.",
      "Browser vs PSA UI."),
     ("TKT-10", "Queue change in the PSA reaches the portal",
      "Move a ticket to another queue in the PSA, changing nothing else, then sync.",
      "The portal shows the new queue.",
      "SQL. This silently failed until the queue joined the update hash."),
     ("TKT-11", "Concurrent edit does not lose data",
      "Change a ticket in the PSA and in the portal at nearly the same time, then sync.",
      "No lost update and no infinite echo loop.",
      "SQL + worker log."),
     ("TKT-12", "Ticket search",
      "Use the header search for a ticket reference and a keyword.",
      "Correct results, scoped to what the user may see.",
      "Browser as two different roles."),
     ("TKT-13", "Reply composer keeps a draft",
      "Type a reply, close the dialog, reopen it.",
      "The draft text is preserved and the launcher shows a draft-in-progress badge.",
      "Browser."),
     ("TKT-14", "Failed send keeps the draft",
      "Disconnect the network, send a reply, then reconnect.",
      "The dialog stays open with the text intact; it closes only on success.",
      "Browser DevTools offline mode."),
    ])

mod("12. Notes, Conversation and Recipients",
    "Public replies reach the client; internal notes must never do so.",
    [
     ("NOTE-01", "Public reply reaches the PSA and the client",
      "Post a public reply as staff.",
      "Appears in the PSA as a public note and is visible to the client user.",
      "PSA UI + client session."),
     ("NOTE-02", "Internal note stays internal",
      "Post an internal note.",
      "Marked internal in the PSA, shown with the amber internal badge to staff, and absent from "
      "the client payload.",
      "Raw JSON in a client session - not just the UI."),
     ("NOTE-03", "Autotask internal-only text is preserved",
      "In Autotask, create a time entry with text in Internal Notes only, then sync.",
      "The internal text is imported, not dropped, and a pointer-only summary such as 'See "
      "Internal Notes' is not duplicated.",
      "Portal thread vs Autotask."),
     ("NOTE-04", "Note title is not duplicated into the body",
      "Post a long note to Autotask from the portal.",
      "Autotask shows it once. The title is truncated on a word boundary, not the first 250 "
      "characters of the body.",
      "Autotask UI. The symptom of the old bug was 'we sent one note but Autotask shows two'."),
     ("NOTE-05", "To and Cc on a public reply",
      "GET /api/tickets/{id}/recipients, choose contacts, send.",
      "Only contacts belonging to that ticket's company are offered, and the email goes to the "
      "chosen recipients.",
      "API + PSA UI. Confirm no contact from another company can be selected."),
     ("NOTE-06", "Recipient support degrades cleanly",
      "Send a public reply on an Autotask ticket.",
      "Autotask does not support note email recipients - the UI reflects that rather than "
      "silently dropping the selection.",
      "Browser."),
     ("NOTE-07", "Conversation shows newest first with Show all",
      "Open a ticket with more than four notes.",
      "The four most recent show, newest first, with a Show all button revealing the rest.",
      "Browser."),
     ("NOTE-08", "Note kinds are visually distinct",
      "View a thread with client, staff, internal and time-entry notes.",
      "Each kind is visually distinguishable.",
      "Browser."),
     ("NOTE-09", "Time on a reply is linked to its note",
      "Send a reply with time logged in one action.",
      "The time entry is linked to that note (NoteId) and the staff thread shows the duration on "
      "the reply.",
      "SQL: select \"NoteId\" from ticket_time_entries order by \"CreatedAt\" desc limit 1."),
     ("NOTE-10", "Note ordering and timestamps",
      "Compare the thread order with the PSA.",
      "Chronology matches; timestamps are the provider's, not the import time.",
      "Browser vs PSA UI."),
    ])

mod("13. Time Tracking",
    "Time is written to the PSA, which is the system of record. Autotask has strict rules that "
    "the portal must satisfy before it will accept an entry.",
    [
     ("TIME-01", "Log time on a ticket",
      "Time panel > log 0.5h with notes, billable.",
      "Created in the PSA and listed in the portal with matching duration.",
      "PSA UI + portal panel."),
     ("TIME-02", "Fractional hours are accepted",
      "Log 0.25h and 0.30h (18 minutes).",
      "Both accepted. The input step must not block them.",
      "Browser. An HTML step of 0.25 silently blocked 18-minute entries."),
     ("TIME-03", "Autotask requires summary notes",
      "Attempt to log time on Autotask with an empty note.",
      "The UI marks Notes required and blocks submit. If a blank still arrives, a factual "
      "placeholder is sent rather than losing the time.",
      "Browser + PSA UI."),
     ("TIME-04", "Resource and role pairing",
      "Configure a technician and a role that the technician does NOT hold, then log time.",
      "The connector uses a role the technician actually holds rather than failing; if they hold "
      "none, a clear setup error is returned.",
      "PSA UI + API message."),
     ("TIME-05", "Missing time-entry resource is explained",
      "Clear DefaultTimeEntryResourceId on an Autotask connection and log time.",
      "A clear message telling the admin where to set it - not a raw 500.",
      "Browser."),
     ("TIME-06", "Retry surfaces the current error",
      "Fail a time entry, fix the configuration, then retry via "
      "POST /api/tickets/{id}/time/{entryId}/retry.",
      "The message shown is from THIS attempt. A stale error from the first failure is a defect.",
      "Compare the row's UpdatedAt with the retry time."),
     ("TIME-07", "Edit a time entry",
      "PUT /api/tickets/{id}/time/{entryId}.",
      "The PSA entry updates and the portal aggregate is RECOMPUTED from the PSA, not adjusted "
      "locally.",
      "PSA UI + portal totals."),
     ("TIME-08", "Delete a time entry",
      "DELETE /api/tickets/{id}/time/{entryId}.",
      "Removed in the PSA and the aggregate recomputed.",
      "PSA UI + portal totals."),
     ("TIME-09", "Work type and role options",
      "GET /api/tickets/{id}/time-options.",
      "Only work types and roles valid for this connection and technician are offered.",
      "API."),
     ("TIME-10", "Global timer",
      "Start the header timer, attach it to a ticket, navigate away, return, then log it.",
      "The timer survives navigation and a page reload, and logs the elapsed time.",
      "Browser (state is persisted in localStorage)."),
     ("TIME-11", "Time logged in the PSA reaches the portal",
      "Add a time entry directly in the PSA, then sync.",
      "Portal totals update. Time refresh is keyed off the ticket being FETCHED, not off the "
      "upsert reporting a change - a time entry changes no hashed field.",
      "Portal totals + SQL."),
     ("TIME-12", "Client never sees time",
      "View a ticket with time entries as a client user.",
      "No time data in the payload at all.",
      "Raw JSON."),
     ("TIME-13", "Permission gating",
      "Attempt to log time as a role without tickets.time.log.",
      "Refused, and the panel is not offered.",
      "Browser + API 403."),
     ("TIME-14", "Billable flag round trip",
      "Log billable and non-billable entries.",
      "Both are reflected correctly in the PSA.",
      "PSA UI."),
    ])

mod("14. Attachments",
    "Upload, scan, store, download and reconcile files on both the staff and client paths.",
    [
     ("ATT-01", "Staff upload",
      "Attach a file to a ticket from the dashboard.",
      "Uploads successfully and appears in the list.",
      "Browser. The staff path was once client-only and every staff attach failed with "
      "'Couldn't send'."),
     ("ATT-02", "Client upload",
      "Attach a file as a client user.",
      "Uploads and is visible to staff.",
      "Browser (both sessions)."),
     ("ATT-03", "Download via signed URL",
      "Request a download URL, then fetch the blob.",
      "The file downloads; the URL is time-limited and cannot be reused after expiry.",
      "API + curl after the expiry window."),
     ("ATT-04", "Oversized file is refused",
      "Upload a file above the configured limit.",
      "Refused with a clear message.",
      "Browser."),
     ("ATT-05", "Quarantined file cannot be downloaded",
      "Upload the EICAR string, then attempt to download it.",
      "Blocked and badged as quarantined.",
      "Browser + SQL."),
     ("ATT-06", "PSA attachment sweep",
      "Add an attachment in the PSA to a ticket nobody has touched, then sync.",
      "It is imported by the dated sweep where the provider supports one (ConnectWise indexes "
      "documents per record and falls back to per-ticket).",
      "Portal + worker log."),
     ("ATT-07", "Deletion reconciliation",
      "Delete an attachment in the PSA and sync.",
      "It is removed from the portal.",
      "SQL on attachments."),
     ("ATT-08", "Attachment upload format per PSA",
      "Attach a file on an Autotask ticket, then on a ConnectWise ticket.",
      "Autotask: JSON body to Tickets/{id}/Attachments with the file base64 in data. ConnectWise: multipart/form-data (its API rejects JSON with 415). Both appear in the PSA with the original file name.",
      "Worker log + PSA UI."),
    ])

mod("15. Productivity and Analytics",
    "The weighted productivity score, team and client views, and PSA-versus-portal coverage.",
    [
     ("ANA-01", "Technician metrics",
      "GET /api/dashboard/technician for a technician with known ticket history.",
      "Counts, SLA percentage, average resolution and logged time match SQL.",
      "API + SQL."),
     ("ANA-02", "Score renormalises over measured components",
      "Inspect the productivity breakdown for a technician with no CSAT data.",
      "Unmeasured components are EXCLUDED rather than scored as zero, and the coverage fraction "
      "is reported.",
      "API response. A score computed over missing data is worse than no score."),
     ("ANA-03", "Disclaimer is always present",
      "Call every dashboard endpoint.",
      "Each response carries the measurement disclaimer.",
      "Raw JSON."),
     ("ANA-04", "Team view and export",
      "GET /api/dashboard/team then /team/export.",
      "The CSV matches the on-screen table exactly, including the header row.",
      "Download and diff."),
     ("ANA-05", "Trend",
      "GET /api/dashboard/trend over a range spanning a data gap.",
      "Gaps are visible as gaps, not interpolated to zero.",
      "API + chart."),
     ("ANA-06", "Client workload ranking",
      "Open /dashboard/analytics/clients.",
      "Clients ranked by hours; sample size shown; unclosable tickets excluded from averages.",
      "Browser + SQL."),
     ("ANA-07", "SLA percentage with no eligible tickets",
      "View a client with zero SLA-eligible tickets.",
      "Shows null / not applicable - never 100 percent.",
      "Browser."),
     ("ANA-08", "Portal versus PSA coverage",
      "Open /dashboard/analytics/coverage.",
      "Coverage percentage plus ticket and day corroboration, and a flag when the range starts "
      "before activity recording began.",
      "Browser. Without that flag the early period looks like poor adoption rather than no data."),
     ("ANA-09", "Own versus team scope",
      "View analytics as a Technician (productivity.own.view) and as a Manager "
      "(productivity.team.view).",
      "The technician sees only themselves.",
      "Browser."),
     ("ANA-10", "Analytics reflect the full ticket set",
      "Compare the ticket count behind analytics with the PSA's own count.",
      "They match. Analytics computed over a truncated import were wrong for months before "
      "pagination was fixed.",
      "SQL vs PSA."),
     ("ANA-11", "Ticket-derived metrics recompute on read",
      "Import more tickets, then reload analytics without any rollup running.",
      "Client workload and technician metrics already reflect the new data.",
      "Browser."),
     ("ANA-12", "Export respects permissions",
      "Request the team export as a Technician.",
      "Refused.",
      "API 403."),
    ])

mod("16. Activity Events and Daily Rollup",
    "An append-only event log rolled into daily facts, with 13-month retention on the raw rows.",
    [
     ("ROLL-01", "Events are captured from both sources",
      "Perform a portal action and let a PSA transition sync.",
      "Rows appear in activity_events with Source Portal and Psa respectively.",
      "SQL: select \"Source\",count(*) from activity_events group by 1."),
     ("ROLL-02", "Events are dated when they HAPPENED",
      "Import a ticket closed last month.",
      "OccurredAt carries last month's date, not today's.",
      "SQL: select \"OccurredAt\"::date, count(*) from activity_events group by 1 order by 1."),
     ("ROLL-03", "Rollup produces daily facts",
      "Wait for the hourly pass or restart the worker.",
      "activity_daily_facts is populated; sum(\"EventCount\") equals the number of events in range.",
      "SQL."),
     ("ROLL-04", "History older than the rolling window is backfilled",
      "Insert an event dated 60 days ago, then run the rollup.",
      "A fact exists for that day. A fixed 7-day window alone can never build history.",
      "SQL."),
     ("ROLL-05", "Backfill settles",
      "Run the rollup twice.",
      "The first pass processes the backlog; the second processes only the rolling window and the "
      "totals do not change.",
      "Compare the two 'Activity rollup:' log lines - capture the first line's timestamp and "
      "poll for a DIFFERENT one, or you will read the same line twice."),
     ("ROLL-06", "Late-arriving events correct their own day",
      "Add a second event for a day already rolled up, then run the rollup.",
      "That day's fact is rebuilt, not appended to.",
      "SQL."),
     ("ROLL-07", "Untouched days keep their facts",
      "Ensure a day inside the rebuild range has facts but no new events.",
      "Its facts survive the pass unchanged.",
      "SQL."),
     ("ROLL-08", "Retention expires raw events but keeps facts",
      "Insert an event older than 396 days and run the rollup.",
      "The raw event is deleted; facts from that period remain.",
      "SQL counts on both tables."),
    ])
